### ISSUE TITLE
Foreground/Sprites/CGAlt get stretched after convertion

### ISSUE THREAD

**Issue by felixsrg** [MyLegGuy/VNDSVitaConverter#1]
Hello, I've been working on fixing some VNs from the original VNDS and then converting them to VNDS Clone Vita format, and everything has been working great.

One thing I've noticed though, is that when converting a novel, all the background/CG *.jpg files convert 1:1 but foreground/sprites/CGAlt *.png files get stretched (One example is: If the VNDS has a img.ini size of 640x480, when converting, foreground images that were 640x480, get stretched to 700x500)

If the converted CGAlt pictures are replaced by the original foreground ones, the novel works perfectly, I just wanted to share this extrange bug.

**Comment by MyLegGuy** [comment]
A long time ago, for some reason, I decided it was a good idea to pad all foreground images' dimensions to the next multiple of 100.
It just adds a bunch of transparency to the edges, but shouldn't stretch the image itself.
I do not remember why I chose to do this.
(My guess is that libvita2d had trouble loading images with weird sizes. But libvita2d has improved a lot since then, so things may work now.)
Anyway, this shouldn't be hurting anything. It's not messing up the positioning, right?
And because it's just transparency, it should compress pretty well.
If somebody used a jpg for a foreground image, however, this will be bad. But I doubt this will ever happen.

I probably should investigate if this is still needed.

**Comment by felixsrg** [comment]
It makes sense, however with all my convertions, I've seen image stretching, sometimes it is varely noticeable, but when stretching, some sprites lose graphic quality and get wider, here's an example from Kanon, for other novels like Kira Kira it is a little more noticeable:

Original:
![CGAK10](https://user-images.githubusercontent.com/32381087/95106578-4ee4a800-06fe-11eb-87a7-0a42d0d8bcee.png)
Converted:
![CGAK10](https://user-images.githubusercontent.com/32381087/95106614-573ce300-06fe-11eb-8c64-749a44ba0d36.png)

When the background images are 640x480, the img.ini has the same size, so when sending a stretched sprite with 700x500 (or bigger X or Y), it sometimes messes the positioning.

**Comment by MyLegGuy** [comment]
That shouldn't be happening. This is super not good, thank you for the report.
I'm busy now, but in a few days I'll look into it.

**Comment by felixsrg** [comment]
No problem, as I was saying, if you know this happens after converting, it is easy to replace the converted sprites with the original ones as a workaround for now.

I want to thank you for making this even possible in first place, I at least am really happy converting and fixing some old VNDS novels.

**Comment by MyLegGuy** [comment]
this should fix the problem:
[fixed.zip](https://github.com/MyLegGuy/VNDSVitaConverter/files/5331428/fixed.zip)

it's nice to know people are still using this. But it seems there's an endless amount of critical bugs, making me wonder if even a single game is fully playable...

**Comment by felixsrg** [comment]
Sorry for the late reply, this indeed fixes the issue, thank you for sharing it!

Don't worry too much about the bugs, most of them come from the original convertion process (From Windows to VNDS format), I have been fixing some of them and can confirm until now, that there novels are fully playable after fixing its original scripting and file structure (most of them had missing files or bad scripts):

Cross+Channel
Kira Kira
Kanon
Fate/stay night

**Comment by MyLegGuy** [comment]
They're broken on other VNDS interpreters too? People have been trading broken games around for over a decade? Huh. Weird indeed.
