### ISSUE TITLE
[Request] Way to unpack "SEArchive.legArchive" file

### ISSUE THREAD

**Issue by felixsrg** [MyLegGuy/VNDSVitaConverter#2]
Hello there, sorry to bother, I was wondering if there is a way to extract the audio files from within the legArchive file.

I've found a novel that was converted to Vita while fixing some missing audio files but all the pre-converted versions are still incomplete. That's the reason I would like to ask if it's possible to get the audio files from an already converted novel.

Thank you in advance for your time.

**Comment by MyLegGuy** [comment]
okay, check out this program i made:
https://github.com/MyLegGuy/legArchive/releases/download/w/legarchive-windows.zip

here is how you use it on windows:

extract archive:
0. download and upzip the linked file
1. hold shift and right click somewhere on the desktop or file explorer. then click "open command prompt" or "open powershell here"
2. drag and drop the "legarchive.exe" from the extracted folder into the command prompt. it will put its path for you.
3. press space, type "extractArchive" (case sensitive) and then another space
4. drag and drop the legarchive file onto the commadn prompt
5. put a space
6. drag and drop the folder you want the files to be extracted to. it should be a new folder if you don't want to clutter everything.
7. press enter.

Example:
```
C:\Users\me\Downloads\legarchive.exe extractArchive C:\Users\me\Downloads\SEArchive.legArchive C:\Users\me\Downloads\outdir\
```

make archive:
same idea as before, but do it like this instead:
```
<path_to_legarchive.exe> makeArchive <source_files_directory> <dest_file_path>
```
just note that you'll have to type the destination file path manually and it should have quotes around it if it's going to include spaces.

notes:
* non-english characters are not supported. if this is the cause of missing files, tell me and i'll rework the code.
* i didn't test it on a real windows installation, so there's a chance it doesn't work. hopefully it's fine though.

**Comment by felixsrg** [comment]
It's working perfectly on Windows, thank you very much!
